#!/bin/bash
#
# This is an example how you can invoke the versioning-tool with a single additional line in your own post-merge script:
#

# ... your own stuff ...

# Is only called by git after a successful merge without conflicts!!! (Post-Commit and Pre-Merge will care about that)
.git/hooks/versioning_tool_post_merge.sh "$@"

# ... your own stuff ...
