#!/bin/sh
#
# This is an example how you can invoke the versioning-tool with a single additional line in your own post-commit script:
#

# ... your own stuff ...

.git/hooks/versioning_tool_prepare_commit_msg.sh "$1"

# ... your own stuff ...
